Updateseed
PeterBaker644/Recipe-Journal pull request #31
Opened 2020-09-07 17:24 UTC by chueny

-SeedDB.js is the final one that we want.  

-NOTE: Please ignore other files...

2020-09-07 18:38 UTC, PeterBaker644 requested changes
Hi Chue, this is looking great! We do need to tweak this though with some changes. The json object needs to be in this exact format:

```
{
    userID: "",
    recipeName: "",
    recipeDescription: "",
    recipeImageUrls: [],
    recipeCategory: "",
    recipeTags: [],
    ingredients: [],
    actions: []
}
```

That being said, I do like the idea of calling the steps instructions. We should bring this up with Gene and see what he thinks.

2020-09-07 20:16 UTC, chueny commented
-updated seed to match gene's model.

NOTE- @PeterBaker644 in your previous email, they are different from Gene's model
- recipeImageUrls: []       vs.     recipePicLinks: []
- actions: []       vs. Actions: []

2020-09-07 23:44 UTC, jkthomps21 approved these changes

2020-09-08 01:44 UTC, PeterBaker644 approved these changes

2020-09-08 01:45 UTC, merged